name: Bug Report
description: 报告一个问题
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: 发生了什么
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: 复现步骤
      placeholder: 1. ... 2. ...
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: 版本/环境
