name: Feature Request
description: 提一个新想法
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: idea
    attributes:
      label: 需求描述
    validations:
      required: true
  - type: textarea
    id: value
    attributes:
      label: 价值与场景
